### ISSUE TITLE
*-LYRAMION.png maps seem to be missing tiles on the edges

### ISSUE THREAD

**Issue by gynvael** [ecraven/amberstar#1]
Hi,

Thanks for uploading these! :)

While all interior/3D maps seem to have a 6-tile wide border, the outside maps don't seem to have them. However probably the script used to generate the PNGs still assumed the *-LYRAMION maps have the border as well and cropped the tilemaps accordingly (which is incorrect).

For example, the 029- should contain Jonathan's House/Villa, but it's not there (see attachment).
![generated_maps_bug](https://user-images.githubusercontent.com/1008844/71350798-650be800-2572-11ea-9b2f-7b3b5542f555.png)

Cheers!

**Comment by ecraven** [comment]
Thanks for the info, should be fixed with latest commit ;)
